### ISSUE TITLE
CD change 2006-2016

### ISSUE THREAD

**Issue by sdimauro** [kuriwaki/cces_cumulative#4]
data set to calculate the change of congressional districts for Congresses 109,110,113,115

**Comment by kuriwaki** [comment]
Remaining tasks on data 

- [ ] Fix mismatch on at-large districts: Figure out why states like Alaska and Montana are getting zeros for some time frames. They should be close to 1. My guess is that there is some discrepancy in naming of districts across Congresses, which leads to mismatches. I can dive in if that is the case. 
- [ ] Distinguish complete zipcode composition changes from vanished districts, through for example the following way: if for congress  c+1 there are zero zipcodes, give it a `NA` rather than a zero.

**Comment by kuriwaki** [comment]
finished reformatting and streamlining with 0cfd0b577a797c200889f77c3b2ea858c9bfb44c
