### ISSUE TITLE
Merge cq and voteview for ICPSR numbers

### ISSUE THREAD

**Issue by Enye92** [kuriwaki/cces_cumulative#6]

**Comment by Enye92** [comment]
Merge house members first.

**Comment by kuriwaki** [comment]
@Enye92  @natkap862  you might start with code like what I started here.  The line starting from `PSEUDO code` is some example code. I don't think it will work exactly as I wrote it because I don't have the dataset at hand, but it might give you an idea

https://gist.github.com/kuriwaki/46db8129bc5c004a1516a43e62497865

**Comment by kuriwaki** [comment]
@Enye92 started some code to merge this in #7 . congrats on the first pull request!

**Comment by kuriwaki** [comment]
closed with 56b008d346b1a26c5d444c7de1d34fbdb426f499
but still need a separate table for challengers

**Comment by kuriwaki** [comment]
closed with 56b008d346b1a26c5d444c7de1d34fbdb426f499
but still need a separate table for challengers
